### ISSUE TITLE
macOS  homebrew installation instructions out of date

### ISSUE THREAD

**Issue by nicerloop** [idc101/git-mkver#12]
Hi,

Homebrew does not allow to install with the provided instructions anymore:

`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of git-mkver formula file from an arbitrary URL is unsupported!  (UsageError)

A real homebrew tap is required.

**Comment by idc101** [comment]
Hi,

Sorry this took a while to fix. This should work now:

```
brew tap idc101/gitmkver
brew install idc101/gitmkver/git-mkver
```

**Comment by nicerloop** [comment]
Please use a Formula not a Cask. see https://github.com/idc101/homebrew-gitmkver/issues/1

**Comment by idc101** [comment]
Changed it to a Formula.
