### ISSUE TITLE
Bang does not increment major version

### ISSUE THREAD

**Issue by ais** [idc101/git-mkver#14]
From [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/#specification):

> If included in the type/scope prefix, breaking changes MUST be indicated by a ! immediately before the :.

_e.g._: `fix(comp)!: Some damned foolish thing`

I would guess another entry is needed here:

https://github.com/idc101/git-mkver/blob/d5b1c4e2e110b08a14f01592d9e87960ee4e78d0/src/main/scala/net/cardnell/mkver/AppConfig.scala#L194

...or this should be something like `BREAKING CHANGE|.+(\\(.+\\))?!:` to prevent multiple increments if both are used:

https://github.com/idc101/git-mkver/blob/d5b1c4e2e110b08a14f01592d9e87960ee4e78d0/src/main/scala/net/cardnell/mkver/AppConfig.scala#L195

I don't feel confident making this change myself.

**Comment by idc101** [comment]
Hi,

Thanks for this. It should be working now in the latest release:
https://github.com/idc101/git-mkver/releases/tag/v1.2.1

**Comment by TheSimpleZ** [comment]
@idc101 The Windows binaries seems to be missing from that release 😕 
Any chance you could add them? As of now, the scoop installation method is failing with a 404 message.

```powershell
-> scoop install https://raw.githubusercontent.com/idc101/git-mkver/master/etc/scoop/git-mkver.json  
Installing 'git-mkver' (1.2.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/idc101/git-mkver/releases/download/v1.2.1/git-mkver-windows-amd64-1.2.1.zip is not valid
```

**Comment by idc101** [comment]
Hi, added them scoop works again now.
