### ISSUE TITLE
git mkver tag silently fails if the commit is already tagged with a prerelease

### ISSUE THREAD

**Issue by TheSimpleZ** [idc101/git-mkver#18]
I made a clean git repo, added a file and a commit with "feat:" in the message. 
Running `git mkver tag --prerelease` yields v0.1.0-pre1 as expected.

However, running `git mkver tag` immediately afterward silently fails. It simply does not create the tag v0.1.0, which is what I would expect. And no error message either.

If I create a new commit, it works fine again. Is this a scenario that git-mkver supports?

**Comment by idc101** [comment]
Hi, yes there is an explicit check that prevents retagging an existing tag. However I agree this should not be the case if the current tag is a pre-release. I'll change this.

**Comment by idc101** [comment]
Hi, please try v1.2.2 and let me know if that fixes it.

**Comment by TheSimpleZ** [comment]
Works great! Thank you :)
