### ISSUE TITLE
Allowing `git-mkver` to keep predicted versions below `1.0.0` for applications in beta

### ISSUE THREAD

**Issue by cortadocodes** [idc101/git-mkver#20]
## Background
I'm developing [an SDK for the wind turbine industry](https://github.com/octue/octue-sdk-python) which is currently in beta. I've also created a package facilitating [continuous deployment based on conventional commits](https://github.com/octue/conventional-commits) that uses `git-mkver` to warn pull request authors if the expected semantic version is out of line with the package version stated in e.g. `setup.py`. 

I'd also like to quickly say I love `git-mkver`! It's a really useful tool for automating releases and it does almost everything I need :green_heart:

## Problem statement
As we're in beta, we want to keep the version below `1.0.0` until we have a stable API. The only way I can do that currently without the warning (mentioned above) triggering is by not including `BREAKING CHANGE` in commit messages because the commit message action for breaking changes is [hardwired in the `mkver.conf` file parser](https://github.com/idc101/git-mkver/blob/60770147d527948afc14094332cfa8c684d7e681/src/main/scala/net/cardnell/mkver/AppConfig.scala#L196). I can add extra actions to the `commitMessageActions` of a `mkver.conf` file but I can't override  any of the default ones.

## Feature request
To be able to specify exactly what triggers a major version (or any other type of version) increase so beta packages can stay under version `1.0.0`. Until today, I thought that [this `mkver.conf`](https://github.com/octue/octue-sdk-python/blob/main/mkver.conf#L25) did this.

## Proposed solution
Allow `defaultCommitMessageActions` to be disabled with a flag in `mkver.conf` so only the `commitMessageActions` a developer specifies in `mkver.conf` are used.

**Comment by idc101** [comment]
Thanks for the feedback!

To get this to work the overrides need to match the patterns exactly in the code. Try this:
```
commitMessageActions: [
  # Disable major version increments while package is still in beta (i.e. keep the version below 1.0.0).
  {
    pattern: "BREAKING CHANGE"
    action: IncrementMinor
  }
  {
    pattern: "BREAKING-CHANGE"
    action: IncrementMinor
  }
```

**Comment by cortadocodes** [comment]
Thank you that works straight away! Is there any chance something about this could be added to the docs (unless it's already there and I missed it)?

**Comment by idc101** [comment]
I've added a section at the bottom of: https://idc101.github.io/git-mkver/config_examples

**Comment by cortadocodes** [comment]
That's great, thank you!
