### ISSUE TITLE
Apple Silicon (M1) support

### ISSUE THREAD

**Issue by cperezabo** [idc101/git-mkver#22]
It doesn't seem to work properly in M1 chips.

<img width="477" alt="CleanShot 2022-02-15 at 18 53 09@2x" src="https://user-images.githubusercontent.com/3604722/154155771-c22df02b-6a2d-4c6c-a5a5-8e8dace9deaf.png">
`

**Comment by idc101** [comment]
Hi,

There isn't an M1 build yet and I don't have an M1 mac. Can you run it under the emulation mode?

**Comment by cperezabo** [comment]
I don't program in either Scala nor Java but I can collaborate by adapting the build process so it supports ARM builds. I can even provide binaries if you don't have an M1 machine or a CI which supports the architecture to automate the process.

At the moment I have been able to run `sbt assembly` using `sbt 1.6.2` and `Java 17.0.2`.
The problems started when I tried to install GraalVM Updater to run `native-image` command on macOS. It seams there isn't an Apple ARM version yet (please, correct me if I'm wrong).

I think there is a "dev" version around but before going that way I would like to know if you know some alternative for that step.

**Comment by idc101** [comment]
Hi, I think the solution for the moment will be to run it as java binaries (i.e. not natively compiled):
1. Compile to a single fat jar
2. Write a shell script to call it
I think sbt has a plugin which will do this. I'll have a look.

**Comment by idc101** [comment]
Hi,

I have added in a new build target which creates a normal java build:
```
sbt universal:packageBin
```
this will create:
```
target/universal/git-mkver-1.2.2.zip
```

if you extract this somewhere then try running:
```
git-mkver-1.2.2/bin/git-mkver
```
I hope this will work as it uses normal java rather than a native binary.

**Comment by cperezabo** [comment]
Hi, I've created #26 with some stuff.
If you don't mind, I could provide you the M1 builds until you get a M1 device or some cloud solution to automate the build.
This project doesn't release so often so it would not be a problem for me.

**Comment by idc101** [comment]
Yes please provide a M1 build for the last release and I will add to the release artifacts.

Thanks for this!

**Comment by cperezabo** [comment]
I upload it here. I don't have any other way of contact
[git-mkver-darwin-arm64-1.2.2.tar.gz](https://github.com/idc101/git-mkver/files/8810175/git-mkver-darwin-arm64-1.2.2.tar.gz)
DARWIN_SHA256=442481a1b439272533ed5dc39bad0bf8d9c8e8b3dcf708df3b68e67112629cce

The only thing left is to update the Homebrew formula to match the OS architecture

**Comment by idc101** [comment]
Thanks, uploaded that. I've also updated homebrew, could you give it a test?

**Comment by cperezabo** [comment]
Works like a charm! Nice job!

<img width="993" alt="CleanShot 2022-06-01 at 21 47 11@2x" src="https://user-images.githubusercontent.com/3604722/171525706-3569b10f-5b5c-4558-8122-b676ea76f644.png">
