### ISSUE TITLE
Git errors are silently discarded

### ISSUE THREAD

**Issue by jbergler** [idc101/git-mkver#3]
Hi there, first of all thank you, I found this tool recently and it's really great. Thank you for sharing your work.

I noticed while trying to integrate this with a CI pipeline that `git mkver tag` wasn't doing anything, but seemed to be succeeding.

After a bunch of debugging I discovered that the git user/email hadn't been set and this line was failing:
https://github.com/idc101/git-mkver/blob/master/src/main/scala/net/cardnell/mkver/Git.scala#L43

I hope to be able to open a PR for this, but in the event I don't find the time I wanted to record the issue and suggest some improved error handling / logging on failures.

**Comment by idc101** [comment]
Hi, thanks for raising. Please check v1.2.0 which should resolve this.

**Comment by jbergler** [comment]
Wonderful, thanks.

(fixed in b3d37ff403d60737ff794bddeb92f0733e4a4b1c)
