### ISSUE TITLE
Access to environment variables

### ISSUE THREAD

**Issue by dagola** [idc101/git-mkver#7]
## Summary
An environment variable defined is not accessible through the `env.XXX` interface.

## Code to reproduce
```
$ mkdir foo
$ cd foo
$ printf 'branches: [\n  {\n    pattern: "master"\n    includeBuildMetaData: false\n    tag: true\n    formats: [\n      { name: Docker, format: "{Version}" }\n      { name: Test, format: "{Version}-{env.BUILD_NUMBER}" }\n    ]\n  }\n]' > mkver.conf
$ touch test
$ git add test
$ git commit -m "chore: Initial commit"
$ BUILD_NUMBER=1
$ git mkver next --format '{Test}'
```
## Expected output
```
0.1.0-1
```

## Actual output 
```
0.1.0-{env.BUILD_NUMBER}
```

**Comment by idc101** [comment]
Hi,

This is due to how shells pass environment variables down to programs. In your example `BUILD_NUMBER` is only available to the shell and not exported to programs launched by the shell. You can either set the variable as you launch the command or export it. e.g.

```bash
 $  BUILD_NO=1
 $  git mkver next -f '{env.BUILD_NO}'
{env.BUILD_NO}
$ BUILD_NO=1 git mkver next -f '{env.BUILD_NO}'
1
$ export BUILD_NO=2
$  git mkver next -f '{env.BUILD_NO}'
2
```

**Comment by dagola** [comment]
Thanks again, @idc101!
