### ISSUE TITLE
Mistake in the installation instructions

### ISSUE THREAD

**Issue by karabanov** [idc101/git-mkver#8]
Hi.

Installation instruction for [Linux ](https://idc101.github.io/git-mkver/installation) has been mistake. URL points to file for macOS
> https://github.com/idc101/git-mkver/releases/download/v1.2.0/git-mkver-darwin-amd64-1.2.0.tar.gz

It's got to be right:
> curl -L https://github.com/idc101/git-mkver/releases/download/v1.2.0/git-mkver-linux-amd64-1.2.0.tar.gz | tar xvz
sudo mv git-mkver /usr/local/bin

**Comment by idc101** [comment]
Thanks! fixed now.
