### ISSUE TITLE
Flag --pre-release don't work with "patch" argument

### ISSUE THREAD

**Issue by karabanov** [idc101/git-mkver#9]
Hi.

If i run `git-mkver next --pre-release` or `git-mkver tag --pre-release` it's work correctly.
But if i run `git-mkver patch --pre-release` nothing happens and the version in the configuration files does not change.

PS
Maybe I'm doing something wrong?

**Comment by idc101** [comment]
Hi,

Can you share your config? I have just tested this:

```bash
$  cat mkver.conf
defaults {
  patches: [
    Docs
  ]
}
patches: [
  {
    name: Docs
    filePatterns: [
      "code.py"
    ]
    replacements: [
      {
        find: "NEXT"
         replace: "{Next}"
      }
   ]
  }
]
$  cat code.py
some other text: NEXT
$  git mkver patch --pre-release
Patching file: 'code.py', new value: '0.1.0-RC1'
$  cat code.py
some other text: 0.1.0-RC1
```
